import { Poppins } from "next/font/google";
import "../globals.css";
import { UiProviders } from "@/Providers/UiProviders";
import Footer from "@/components/shared/footer/Footer";
import MainHeader from "@/components/shared/header/MainHeader/MainHeader";
import BreadCrumbs from "@/components/shared/breadCrumbs/BreadCrumbs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Eco bazar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UiProviders>
          <MainHeader />
          <BreadCrumbs />
          {children}
          <Footer />
        </UiProviders>
      </body>
    </html>
  );
}
